## **EXERCÍCIO 03 - Basic PyTorch**

## **CESAR SCHOOL**
* Pós-graduação em Engenharia e Análise de Dados - 2023.2
* **Disciplina: Tópicos Complementares**
* Professor: **Silvan Ferreira**
* Aluno: **Allan Bispo** - apsb@cesar.school

In [ ]:
# Importando PyTorch
import torch

# Introdução ao PyTorch

## O que é PyTorch?
PyTorch é uma biblioteca de aprendizado profundo de código aberto desenvolvida pelo Facebook's AI Research lab (FAIR). Ela é amplamente utilizada para tarefas de visão computacional e processamento de linguagem natural.

### História e contexto
PyTorch foi lançado em janeiro de 2017. Ele é baseado na biblioteca Torch, que é uma estrutura de aprendizado de máquina em Lua. PyTorch é conhecido por sua facilidade de uso e integração com Python, o que o torna popular entre pesquisadores e engenheiros.

### Comparação com outras bibliotecas
- **TensorFlow**: Desenvolvido pelo Google, TensorFlow é uma das bibliotecas de aprendizado profundo mais populares. Enquanto TensorFlow é conhecido por sua escalabilidade e produção, PyTorch é elogiado por sua facilidade de uso e flexibilidade.
- **NumPy**: NumPy é uma biblioteca fundamental para computação científica em Python. PyTorch usa tensores, que são similares aos arrays do NumPy, mas com suporte para computação em GPU.

## O que são tensores?
Tensores são a estrutura de dados fundamental em PyTorch. Eles são similares aos arrays do NumPy, mas com suporte para computação em GPU.

Tensores 1D, 2D, 3D, etc.
- 1D: Vetores
- 2D: Matrizes
- 3D: Matrizes tridimensionais (cubos de dados)
- ND: Tensores de N dimensões

In [ ]:
# Tensor 1D
tensor_1d = torch.tensor([1, 2, 3, 4])
print(tensor_1d)

tensor([1, 2, 3, 4])


In [ ]:
# Tensor 2D
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor_2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# Tensor 3D
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor_3d)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


### Tipos de dados
Os tensores em PyTorch suportam vários tipos de dados, como inteiros e floats. O tipo de dado pode ser especificado durante a criação do tensor.

In [ ]:
# Criação de um tensor de inteiros
tensor_int = torch.tensor([1, 2, 3], dtype=torch.int32)
print(tensor_int)

tensor([1, 2, 3], dtype=torch.int32)


In [ ]:
# Criação de um tensor de floats
tensor_float = torch.tensor([1, 2, 3], dtype=torch.float32)
print(tensor_float)

tensor([1., 2., 3.])


## Propriedade requires_grad
A propriedade `requires_grad` em PyTorch é fundamental para a construção e treinamento de redes neurais, pois permite calcular automaticamente os gradientes das operações. Quando `requires_grad` é definido como `True` em um tensor, todas as operações feitas nesse tensor serão rastreadas para a diferenciação automática.

### Criando Tensores com `requires_grad`

Vamos criar tensores com a propriedade `requires_grad` definida como `True`:

In [ ]:
# Tensor com requires_grad
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print(x)

tensor([1., 2., 3.], requires_grad=True)


### Realizando Operações com Tensores que Têm `requires_grad`

Quando realizamos operações com tensores que têm `requires_grad=True`, o PyTorch cria uma tape (fita) para rastrear todas as operações. Vamos ver um exemplo:

In [ ]:
# Realiza uma operação com o tensor x
y = x ** 2

# Mais uma operação
z = y.sum()

print(z)

tensor(14., grad_fn=<SumBackward0>)


### Calculando Gradientes

Para calcular os gradientes, usamos o método `backward()`. Isso calcula o gradiente da função de perda em relação a todos os tensores que têm `requires_grad=True`.

Os gradientes armazenados em `x.grad` representam a derivada da soma `z` em relação a `x`. Como `z` é a soma dos elementos de `y` e `y = x ** 2`, a derivada de `z` em relação a `x` é `2 * x`.

In [ ]:
# Calcula os gradientes
z.backward()

# Imprime os gradientes armazenados em x.grad
print(x.grad)

tensor([2., 4., 6.])


### Desativando o Rastreamento de Gradientes

Em algumas situações, não queremos rastrear as operações, como durante a inferência do modelo. Podemos desativar temporariamente o rastreamento de gradientes usando `torch.no_grad()` ou `detach()`. Vamos ver como:

In [ ]:
# Desativando o rastreamento de gradientes temporariamente
with torch.no_grad():
    y = x * 2
    print(y.requires_grad)  # False, pois o rastreamento está desativado

# Criando um novo tensor sem rastreamento de gradientes
x_detached = x.detach()
print(x_detached.requires_grad)  # False, pois o tensor foi separado da tape de computação

False
False


### Verificando se um Tensor Requer Gradiente

Podemos verificar se um tensor requer gradiente usando a propriedade `requires_grad`:

In [ ]:
print(x.requires_grad)  # True, pois x foi criado com requires_grad=True
print(x_detached.requires_grad)  # False, pois x_detached foi separado da tape de computação

True
False


## Funções de Criação de Tensores
PyTorch fornece várias funções utilitárias para criar tensores de forma eficiente.

- `torch.zeros`: Cria um tensor preenchido com zeros.
- `torch.zeros_like`: Cria um tensor preenchido com zeros, com as mesmas dimensões de um tensor dado.
- `torch.ones`: Cria um tensor preenchido com uns.
- `torch.ones_like`: Cria um tensor preenchido com uns, com as mesmas dimensões de um tensor dado.
- `torch.linspace`: Cria um tensor com valores linearmente espaçados entre dois pontos.
- `torch.arange`: Cria um tensor com valores em uma faixa específica com um passo definido.

In [ ]:
# Criação de tensores de zeros
tensor_zeros = torch.zeros(3, 3)
print(tensor_zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# Criação de tensores de zeros_like
tensor_zeros_like = torch.zeros_like(tensor_2d)
print(tensor_zeros_like)

tensor([[0, 0, 0],
        [0, 0, 0]])


In [ ]:
# Criação de tensores de uns
tensor_ones = torch.ones(2, 2)
print(tensor_ones)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# Criação de tensores de ones_like
tensor_ones_like = torch.ones_like(tensor_2d)
print(tensor_ones_like)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [ ]:
# Linspace
tensor_linspace = torch.linspace(0, 10, steps=5)
print(tensor_linspace)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [ ]:
# Arange
tensor_arange = torch.arange(0, 10, step=2)
print(tensor_arange)

tensor([0, 2, 4, 6, 8])


## Indexação e Fatiamento
A indexação e o fatiamento em PyTorch são similares ao NumPy, permitindo acessar e modificar partes específicas de um tensor.

In [ ]:
# Tensor exemplo
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Indexação
print(tensor[0, :])  # Primeira linha
print(tensor[:, 1])  # Segunda coluna

# Fatiamento
print(tensor[1:, 1:])  # Subtensor a partir da segunda linha e segunda coluna

tensor([1, 2, 3])
tensor([2, 5, 8])
tensor([[5, 6],
        [8, 9]])


## Operações básicas com tensores
PyTorch suporta várias operações básicas com tensores, como adição, multiplicação, subtração e divisão.

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Adição
print("+", a + b)

# Multiplicação
print("*", a * b)

# Subtração
print("-", a - b)

# Divisão
print("/", a / b)

+ tensor([5, 7, 9])
* tensor([ 4, 10, 18])
- tensor([-3, -3, -3])
/ tensor([0.2500, 0.4000, 0.5000])


## Manipulando formato (shape)

In [ ]:
tensor = torch.arange(12).reshape(4, 3)
print(tensor)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


### View
A função view em PyTorch permite alterar a forma (shape) de um tensor sem alterar seus dados subjacentes. É semelhante ao método reshape do NumPy.

In [ ]:
# View
tensor_reshaped = tensor.view(6, 2)
print(tensor_reshaped)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])


### Transpose
A função transpose retorna um novo tensor com as dimensões transpostas.

In [ ]:
# Transpose
tensor_transposed = tensor.t()
print(tensor_transposed)

tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])


### Flatten
A função flatten retorna um tensor 1D contendo todos os elementos do tensor original

In [ ]:
# Flatten
tensor_flattened = tensor.flatten()
print(tensor_flattened)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [ ]:
# Reshape
tensor_reshaped = tensor.reshape(1, 2, 6, 1)
print(tensor_reshaped)
print(tensor_reshaped.shape)

tensor([[[[ 0],
          [ 1],
          [ 2],
          [ 3],
          [ 4],
          [ 5]],

         [[ 6],
          [ 7],
          [ 8],
          [ 9],
          [10],
          [11]]]])
torch.Size([1, 2, 6, 1])


### Squeeze e Unsqueeze
- `squeeze`: Remove dimensões de tamanho 1 de um tensor.
- `unsqueeze`: Adiciona uma dimensão de tamanho 1 em um tensor.

In [ ]:
# Squeeze
tensor_squeezed = tensor_reshaped.squeeze()
print(tensor_squeezed)
print(tensor_squeezed.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])


In [ ]:
# Unsqueeze
tensor_unsqueezed = tensor_squeezed.unsqueeze(dim=0)
print(tensor_unsqueezed)
print(tensor_unsqueezed.shape)

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]]])
torch.Size([1, 2, 6])


## Broadcasting
O broadcasting é uma técnica que permite que tensores de diferentes formas sejam utilizados juntos em operações aritméticas. Em vez de copiar dados, o PyTorch ajusta os tensores de forma automática para que tenham formas compatíveis.

### Adição de um Escalar

Quando adicionamos um escalar a um tensor, o escalar é automaticamente expandido para a forma do tensor:

In [ ]:
# Cria um tensor 2x3
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Adiciona um escalar
scalar = 10

# Broadcasting para adicionar o escalar a cada elemento do tensor
result = tensor + scalar
print(result)

tensor([[11, 12, 13],
        [14, 15, 16]])


### Adição de Tensores com Diferentes Dimensões

Vamos adicionar um tensor 2x3 com um tensor 1x3. Neste caso, o tensor 1x3 será expandido (broadcasted) para uma forma 2x3:

In [ ]:
# Cria um tensor 2x3
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Cria um tensor 1x3
tensor_b = torch.tensor([10, 20, 30])

# Broadcasting para adicionar tensores de diferentes formas
result = tensor_a + tensor_b
print(result)

tensor([[11, 22, 33],
        [14, 25, 36]])


### Regras de Broadcasting

Para que o broadcasting funcione, os tensores devem seguir algumas regras:

1. **Compatibilidade de Dimensões**: As dimensões dos tensores devem ser compatíveis. Duas dimensões são compatíveis se forem iguais ou se uma delas for 1.
2. **Expansão Automática**: Se uma dimensão de um tensor for 1, ela será expandida para corresponder à dimensão do outro tensor.

No exemplo a seguir, o tensor `tensor_c` de forma 2x1 é expandido para 2x3, e o tensor `tensor_d` de forma 1x3 é expandido para 2x3. O resultado é um tensor 2x3 onde cada elemento é o produto dos elementos correspondentes.

In [ ]:
# Cria um tensor 2x1
tensor_c = torch.tensor([[1], [2]])

# Cria um tensor 1x3
tensor_d = torch.tensor([10, 20, 30])

# Broadcasting para multiplicar tensores de diferentes formas
result = tensor_c * tensor_d
print(result)

tensor([[10, 20, 30],
        [20, 40, 60]])


## Operações de Redução em PyTorch

As operações de redução são usadas para reduzir as dimensões de um tensor, aplicando operações como soma, média, mínimo e máximo. Essas operações são fundamentais em várias aplicações de machine learning e deep learning.

In [ ]:
# Cria um tensor 2x3
tensor = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print("Tensor original:\n", tensor)
print(tensor.shape)

Tensor original:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


### Soma de Todos os Elementos

A função `torch.sum` calcula a soma de todos os elementos do tensor:

In [ ]:
# Soma de todos os elementos do tensor
sum_all = torch.sum(tensor)
print("Soma de todos os elementos:", sum_all.item())

Soma de todos os elementos: 21.0


### Soma ao Longo de um Eixo

Podemos calcular a soma ao longo de um eixo específico, usando o parâmetro `dim`:

In [ ]:
# Soma ao longo do eixo 0 (linhas)
sum_dim0 = torch.sum(tensor, dim=0)
print("Soma ao longo do eixo 0 (linhas):", sum_dim0)
print(sum_dim0.shape)

Soma ao longo do eixo 0 (linhas): tensor([5., 7., 9.])
torch.Size([3])


In [ ]:
# Soma ao longo do eixo 1 (colunas)
sum_dim1 = torch.sum(tensor, dim=1)
print("Soma ao longo do eixo 1 (colunas):", sum_dim1)
print(sum_dim1.shape)

Soma ao longo do eixo 1 (colunas): tensor([ 6., 15.])
torch.Size([2])


### Média dos Elementos

A função `torch.mean` calcula a média dos elementos do tensor:

In [ ]:
# Média de todos os elementos do tensor
mean_all = torch.mean(tensor)
print("Média de todos os elementos:", mean_all.item())

Média de todos os elementos: 3.5


In [ ]:
# Média ao longo do eixo 0 (linhas)
mean_dim0 = torch.mean(tensor, dim=0)
print("Média ao longo do eixo 0 (linhas):", mean_dim0)
print(mean_dim0.shape)

Média ao longo do eixo 0 (linhas): tensor([2.5000, 3.5000, 4.5000])
torch.Size([3])


In [ ]:
# Média ao longo do eixo 1 (colunas)
mean_dim1 = torch.mean(tensor, dim=1)
print("Média ao longo do eixo 1 (colunas):", mean_dim1)
print(mean_dim1.shape)

Média ao longo do eixo 1 (colunas): tensor([2., 5.])
torch.Size([2])


### Valor Mínimo e Máximo

Podemos encontrar o valor mínimo e máximo de um tensor usando `torch.min` e `torch.max`:

In [ ]:
# Valor mínimo de todos os elementos do tensor
min_all = torch.min(tensor)
print("Valor mínimo de todos os elementos:", min_all)
print()

# Valor máximo de todos os elementos do tensor
max_all = torch.max(tensor)
print("Valor máximo de todos os elementos:", max_all)
print()

# Valor mínimo ao longo do eixo 0 (linhas)
min_dim0, min_indices_dim0 = torch.min(tensor, dim=0)
print("Valor mínimo ao longo do eixo 0 (linhas):", min_dim0)
print("Índices dos valores mínimos ao longo do eixo 0 (linhas):", min_indices_dim0)
print()

# Valor máximo ao longo do eixo 1 (colunas)
max_dim1, max_indices_dim1 = torch.max(tensor, dim=1)
print("Valor máximo ao longo do eixo 1 (colunas):", max_dim1)
print("Índices dos valores máximos ao longo do eixo 1 (colunas):", max_indices_dim1)

Valor mínimo de todos os elementos: tensor(1.)

Valor máximo de todos os elementos: tensor(6.)

Valor mínimo ao longo do eixo 0 (linhas): tensor([1., 2., 3.])
Índices dos valores mínimos ao longo do eixo 0 (linhas): tensor([0, 0, 0])

Valor máximo ao longo do eixo 1 (colunas): tensor([3., 6.])
Índices dos valores máximos ao longo do eixo 1 (colunas): tensor([2, 2])


### Produto dos Elementos

A função `torch.prod` calcula o produto de todos os elementos do tensor:

In [ ]:
# Produto de todos os elementos do tensor
prod_all = torch.prod(tensor)
print("Produto de todos os elementos:", prod_all)
print()

# Produto ao longo do eixo 0 (linhas)
prod_dim0 = torch.prod(tensor, dim=0)
print("Produto ao longo do eixo 0 (linhas):", prod_dim0)
print()

# Produto ao longo do eixo 1 (colunas)
prod_dim1 = torch.prod(tensor, dim=1)
print("Produto ao longo do eixo 1 (colunas):", prod_dim1)

Produto de todos os elementos: tensor(720.)

Produto ao longo do eixo 0 (linhas): tensor([ 4., 10., 18.])

Produto ao longo do eixo 1 (colunas): tensor([  6., 120.])


## Exercícios - PyTorch Básico

### Exercício 1: Criação de Tensores

1. Crie um tensor 1D com os valores de 1 a 10.
2. Crie um tensor 2D de forma (3, 3) com valores aleatórios.
3. Crie um tensor 3D de forma (2, 3, 4) com todos os valores iguais a 1.
4. Crie um tensor de zeros com as mesmas dimensões do tensor 2D criado no exercício 2.
5. Crie um tensor de uns com as mesmas dimensões do tensor 3D criado no exercício 3.

In [ ]:
# Exercício 1: Criação de Tensores
# 1. Crie um tensor 1D com os valores de 1 a 10

ex_1_1 = torch.tensor([1,3,5,7,9])
ex_1_1_arange = torch.arange(1,10,2)
print(ex_1_1)
print(ex_1_1_arange)

tensor([1, 3, 5, 7, 9])
tensor([1, 3, 5, 7, 9])


In [ ]:
# Exercício 1: Criação de Tensores
# 2. Crie um tensor 2D de forma (3, 3) com valores aleatórios.

ex_1_2 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
ex_1_2_randint = torch.randint(low=1, high=100, size=(3, 3))
print(ex_1_2)
print(ex_1_2_randint)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[70,  1, 98],
        [16, 92, 90],
        [83, 95, 54]])


In [ ]:
# Exercício 1: Criação de Tensores
# 3. Crie um tensor 3D de forma (2, 3, 4) com todos os valores iguais a 1.

ex_1_3 = torch.ones(2, 3, 4)
print(ex_1_3)
print(ex_1_3.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([2, 3, 4])


In [ ]:
# Exercício 1: Criação de Tensores
# 4. Crie um tensor de zeros com as mesmas dimensões do tensor 2D criado no exercício 2.

ex_1_4 = torch.zeros_like(ex_1_2)
print(ex_1_4)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
# Exercício 1: Criação de Tensores
# 5. Crie um tensor de uns com as mesmas dimensões do tensor 3D criado no exercício 3.

ex_1_5 = torch.ones_like(ex_1_3)
print(ex_1_5)
print(ex_1_5.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([2, 3, 4])


### Exercício 2: Manipulação de Tensores

1. Dado o tensor `a = torch.tensor([[1, 2], [3, 4], [5, 6]])`, obtenha a primeira coluna.
2. Dado o tensor `b = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])`, obtenha o subtensor `[[7, 8, 9], [10, 11, 12]]`.
3. Dado o tensor `c = torch.tensor([1, 2, 3, 4, 5, 6])`, mude sua forma para (2, 3).
4. Dado o tensor `d = torch.tensor([1, 2, 3, 4, 5, 6])`, adicione uma dimensão extra para que ele se torne de forma (1, 6).

In [ ]:
# Exercício 2: Manipulação de Tensores
# 1. Dado o tensor a = torch.tensor([[1, 2], [3, 4], [5, 6]]), obtenha a primeira coluna.

a = torch.tensor([[1, 2], [3, 4], [5, 6]])

ex_2_1 = a[:,0]
print(ex_2_1)

tensor([1, 3, 5])


In [ ]:
# Exercício 2: Manipulação de Tensores
# 2. Dado o tensor b = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]), obtenha o subtensor [[7, 8, 9], [10, 11, 12]].

b = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

ex_2_2 = b[1:]
print(ex_2_2)

tensor([[[ 7,  8,  9],
         [10, 11, 12]]])


In [ ]:
# Exercício 2: Manipulação de Tensores
# 3. Dado o tensor c = torch.tensor([1, 2, 3, 4, 5, 6]), mude sua forma para (2, 3).

c = torch.tensor([1, 2, 3, 4, 5, 6])

ex_2_3 = c.reshape(2, 3)
print(ex_2_3)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# Exercício 2: Manipulação de Tensores
# 4. Dado o tensor d = torch.tensor([1, 2, 3, 4, 5, 6]), adicione uma dimensão extra para que ele se torne de forma (1, 6).

d = torch.tensor([1, 2, 3, 4, 5, 6])

ex_2_4 = d.unsqueeze(dim=0)
print(ex_2_4)
print(ex_2_4.shape)

tensor([[1, 2, 3, 4, 5, 6]])
torch.Size([1, 6])


### Exercício 3: Funções de Criação de Tensores

1. Crie um tensor contendo valores de 0 a 1, espaçados igualmente em 5 passos.
2. Crie um tensor contendo valores de 0 a 10, com um passo de 2.
3. Crie um tensor de forma (3, 3) com valores aleatórios entre 0 e 10.
4. Crie um tensor correspondente a uma imagem em escala de cinza de dimensões 128x128 com valores aleatórios entre 0 e 255.
5. Crie um tensor correspondente a uma imagem em RGB de dimensões 128x128 com valores aleatórios entre 0 e 255.

In [ ]:
# Exercício 3: Funções de Criação de Tensores
# 1. Crie um tensor contendo valores de 0 a 1, espaçados igualmente em 5 passos.

ex_3_1 = torch.arange(0, 1, step=0.2)
print(ex_3_1)

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000])


In [ ]:
# Exercício 3: Funções de Criação de Tensores
# 2. Crie um tensor contendo valores de 0 a 10, com um passo de 2.

ex_3_2 = torch.arange(0, 10, step = 2)
print(ex_3_2)

tensor([0, 2, 4, 6, 8])


In [ ]:
# Exercício 3: Funções de Criação de Tensores
# 3. Crie um tensor de forma (3, 3) com valores aleatórios entre 0 e 10.

ex_3_3 = torch.randint(low=0, high=10, size=(3, 3))
print(ex_3_3)

tensor([[9, 4, 8],
        [4, 2, 8],
        [0, 3, 1]])


In [ ]:
# Exercício 3: Funções de Criação de Tensores
# 4. Crie um tensor correspondente a uma imagem em escala de cinza de dimensões 128x128 com valores aleatórios entre 0 e 255.

ex_3_4 = torch.randint(low = 0, high = 255, size = (128, 128))
print(ex_3_4)
print(ex_3_4.shape)

tensor([[188, 230, 175,  ...,  12, 198, 191],
        [158, 163,  59,  ..., 137,  99, 109],
        [160,   8,  59,  ...,  21, 186, 116],
        ...,
        [ 12,  20, 174,  ..., 233,  77,  80],
        [166, 185, 224,  ..., 213, 142,  74],
        [ 65,  29, 126,  ..., 170,  50, 204]])
torch.Size([128, 128])


In [ ]:
# Exercício 3: Funções de Criação de Tensores
# 5. Crie um tensor correspondente a uma imagem em RGB de dimensões 128x128 com valores aleatórios entre 0 e 255.

ex_3_5 = torch.randint(low = 0, high = 255, size = (128, 128, 3))
print(ex_3_5)
print(ex_3_5.shape)

tensor([[[ 10, 133,  68],
         [ 20, 146, 243],
         [ 61,  95,  31],
         ...,
         [141, 120, 199],
         [ 42,  38, 207],
         [201, 227, 254]],

        [[251,  95,  63],
         [167, 238,  19],
         [146, 124, 162],
         ...,
         [ 12,  62, 179],
         [ 81, 126, 124],
         [220,  18, 146]],

        [[176, 196, 127],
         [115, 241, 185],
         [ 79,  79,  84],
         ...,
         [ 38, 141,  83],
         [125, 139,  80],
         [117, 155, 133]],

        ...,

        [[149,  61,  36],
         [108, 122, 147],
         [ 93,  66, 192],
         ...,
         [ 87, 191, 229],
         [ 72, 252,  63],
         [227,  39, 106]],

        [[ 54,  24, 108],
         [ 62, 167, 154],
         [216,  15, 117],
         ...,
         [104, 115, 134],
         [211,  35,   5],
         [101,  48,   1]],

        [[177, 128, 218],
         [246,  70,  76],
         [  0, 214,  50],
         ...,
         [115, 113,  22],
        

### Exercício 4: Operações Avançadas com Tensores

1. Dado o tensor `a = torch.tensor([1, 2, 3])` e `b = torch.tensor([[4], [5], [6]])`, calcule a soma de `a` e `b` usando broadcasting.
2. Dado o tensor `a = torch.tensor([1.0, 2.0, 3.0, 4.0])`, calcule a soma de todos os elementos.
3. Dado o tensor `a = torch.tensor([1.0, 2.0, 3.0, 4.0])`, calcule a média de todos os elementos.
4. Dado o tensor `a = torch.tensor([1.0, 2.0, 3.0, 4.0])`, calcule a raiz quadrada de todos os elementos.

In [ ]:
# Exercício 4: Operações Avançadas com Tensores
# 1. Dado o tensor a = torch.tensor([1, 2, 3]) e b = torch.tensor([[4], [5], [6]]), calcule a soma de a e b usando broadcasting.

a = torch.tensor([1, 2, 3])
b = torch.tensor([[4], [5], [6]])

ex_4_1 = a + b
print(ex_4_1)

tensor([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]])


In [ ]:
#  Exercício 4: Operações Avançadas com Tensores
# 2. Dado o tensor a = torch.tensor([1.0, 2.0, 3.0, 4.0]), calcule a soma de todos os elementos.

a = torch.tensor([1.0, 2.0, 3.0, 4.0])

ex_4_2 = torch.sum(a)
print(ex_4_2)

tensor(10.)


In [ ]:
# Exercício 4: Operações Avançadas com Tensores
# 3. Dado o tensor a = torch.tensor([1.0, 2.0, 3.0, 4.0]), calcule a média de todos os elementos.

a = torch.tensor([1.0, 2.0, 3.0, 4.0])

ex_4_3 = torch.mean(a)
print(ex_4_3)

tensor(2.5000)


In [ ]:
# Exercício 4: Operações Avançadas com Tensores
# 4. Dado o tensor a = torch.tensor([1.0, 2.0, 3.0, 4.0]), calcule a raiz quadrada de todos os elementos.

a = torch.tensor([1.0, 2.0, 3.0, 4.0])

ex_4_4 = torch.sqrt(a)
print(ex_4_4)

tensor([1.0000, 1.4142, 1.7321, 2.0000])


### Exercício 5: Autograd e Backpropagation

1. Crie um tensor `x` com os valores `[2.0, 3.0]` e `requires_grad=True`. Calcule `y = x^2` e os gradientes.
2. Crie um tensor `x` com o valor `3.0` e `requires_grad=True`. Calcule `y = 2*x + 1` e o gradiente.
3. Crie um tensor `x` com os valores `[1.0, 2.0, 3.0]` e `requires_grad=True`. Calcule `y = x^3` e os gradientes.

In [ ]:
# Exercício 5: Autograd e Backpropagation
# 1. Crie um tensor x com os valores [2.0, 3.0] e requires_grad=True. Calcule y = x^2 e os gradientes.

x = torch.tensor([2.0, 3.0], requires_grad=True)

y = x ** 2

z = y.sum()
z.backward()

ex_5_1 = x.grad
print(ex_5_1)

tensor([4., 6.])


In [ ]:
# Exercício 5: Autograd e Backpropagation
# 2. Crie um tensor x com o valor 3.0 e requires_grad=True. Calcule y = 2*x + 1 e o gradiente.

x = torch.tensor([3.0], requires_grad=True)
y = 2*x + 1
z = y.sum()
z.backward()

ex_5_2 = x.grad
print(ex_5_2)

tensor([2.])


In [ ]:
# Exercício 5: Autograd e Backpropagation
# 3. Crie um tensor x com os valores [1.0, 2.0, 3.0] e requires_grad=True. Calcule y = x^3 e os gradientes.

x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x**3

z = y.sum()
z.backward()

ex_5_3 = x.grad
print(ex_5_3)

tensor([ 3., 12., 27.])


### Exercício 6: Operações de Redução

1. Crie um tensor de forma (4, 5) contendo valores de 1 a 20 usando `torch.arange`. Em seguida, calcule a soma de todos os elementos do tensor.

2. Crie um tensor de forma (3, 4) com valores aleatórios entre 0 e 1 usando `torch.rand`. Calcule a média dos elementos ao longo do eixo 1 (colunas).

3. Crie um tensor de forma (5, 5) contendo valores espaçados igualmente de 0 a 24 usando `torch.linspace`. Encontre o valor mínimo e o máximo de todos os elementos do tensor.

4. Crie um tensor de forma (3, 6) com valores inteiros aleatórios entre 10 e 50 usando `torch.randint`. Calcule o produto dos elementos ao longo do eixo 0 (linhas).

5. Crie um tensor de forma (2, 3, 4) com valores aleatórios entre 0 e 1 usando `torch.rand`. Encontre a soma dos elementos ao longo do eixo 2.

In [ ]:
# Exercício 6: Operações de Redução
# 1. Crie um tensor de forma (4, 5) contendo valores de 1 a 20 usando torch.arange. Em seguida, calcule a soma de todos os elementos do tensor.

x = torch.arange(1, 21, 1).reshape(4, 5)

ex_6_1 = x.sum()
print(ex_6_1)

tensor(210)


In [ ]:
# Exercício 6: Operações de Redução
# 2. Crie um tensor de forma (3, 4) com valores aleatórios entre 0 e 1 usando torch.rand. Calcule a média dos elementos ao longo do eixo 1 (colunas).

x = torch.rand(3, 4)

ex_6_2 = x.mean(dim=1)
print(ex_6_2)
print(x)

tensor([0.5131, 0.5265, 0.4722])
tensor([[0.3778, 0.2424, 0.6076, 0.8248],
        [0.0979, 0.9349, 0.8427, 0.2306],
        [0.1248, 0.6525, 0.6603, 0.4512]])


In [ ]:
# Exercício 6: Operações de Redução
# 3. Crie um tensor de forma (5, 5) contendo valores espaçados igualmente de 0 a 24 usando torch.linspace.
#       Encontre o valor mínimo e o máximo de todos os elementos do tensor.

ex_6_3 = torch.linspace(0, 24, steps = 25)

print(ex_6_3.min())
print(ex_6_3.max())

tensor(0.)
tensor(24.)


In [ ]:
# Exercício 6: Operações de Redução
# 4. Crie um tensor de forma (3, 6) com valores inteiros aleatórios entre 10 e 50 usando torch.randint.
#     Calcule o produto dos elementos ao longo do eixo 0 (linhas).

x = torch.randint(low = 10, high = 50, size = (3, 6))
ex_6_4 = x.prod(dim=0)
print(ex_6_4)
print(x)

tensor([20280, 15600,  3900,  7744, 12250, 10906])
tensor([[26, 25, 25, 44, 25, 19],
        [26, 24, 13, 11, 35, 14],
        [30, 26, 12, 16, 14, 41]])


In [ ]:
# Exercício 6: Operações de Redução
# 5. Crie um tensor de forma (2, 3, 4) com valores aleatórios entre 0 e 1 usando torch.rand.
#     Encontre a soma dos elementos ao longo do eixo 2.

x = torch.rand(2, 3, 4)

ex_6_5 = x.sum(dim=2)
print(ex_6_5)

tensor([[2.5701, 2.5722, 1.3104],
        [2.8468, 1.9729, 0.7142]])
